# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88154abb0e204db7840d8c66ee75a9960fc551a8883eb85dd420229e4a174e4dc79cdc66c3900a4e0247a572b8582e6bb7bdf945686f51dec506310acb4bbc94

test:
  secret_key_base: 20e1b46df9b2e0b7d8ea5caf790fbcb67b64b9a47e626c4384df149575c60e1d42ca90d81d81d97d0db730d5f95e5f5b17c17131ae023529f9c6dddfa9bb2c04

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
